name: RedisJoin
version: '${version}'
main: com.ericlmao.redisjoin.RedisJoinPlugin
api-version: '1.21'
authors: ["ericlmao"]
dependencies:
  server:
    PlaceholderAPI:
      load: AFTER
      required: false
